#!/usr/bin/env python3
"""
Regenerate references/methods.md from the rr_netconf_mgmt sources (no device needed).

    .venv/bin/python skills/netconf/scripts/gen_catalog.py            # rewrite
    .venv/bin/python skills/netconf/scripts/gen_catalog.py --check    # exit 1 if stale

Needs the interpreter that has libyang/ncclient installed (the library imports them at module level).
"""

from __future__ import annotations

import inspect
import sys
from pathlib import Path

SKILL_DIR = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(SKILL_DIR / "rac_netconf_mgmt" / "src"))

from rr_netconf_mgmt import exceptions  # noqa: E402
from rr_netconf_mgmt.config import NetconfConfig, SchemaFetcherProtocol  # noqa: E402
from rr_netconf_mgmt.device import NetconfDevice  # noqa: E402

OUT = SKILL_DIR / "references" / "methods.md"
DESTRUCTIVE = {"set_config"}


def first_line(doc: str | None) -> str:
    for line in inspect.cleandoc(doc or "").splitlines():
        if line.strip():
            return line.strip()
    return ""


def sig(fn) -> str:  # noqa: ANN001
    if isinstance(fn, property):
        return " (property)"
    s = inspect.signature(fn)
    params = [p for n, p in s.parameters.items() if n not in ("self", "cls")]
    text = str(s.replace(parameters=params))
    for prefix in ("rr_netconf_mgmt.config.", "rr_netconf_mgmt.device.", "typing.", "collections.abc."):
        text = text.replace(prefix, "")
    return text


def members(cls: type) -> list[tuple[str, object, str]]:
    rows = []
    for name, member in vars(cls).items():
        if name.startswith("_") and name not in ("__init__", "__enter__"):
            continue
        if isinstance(member, classmethod):
            rows.append((name, member.__func__, "classmethod"))
        elif isinstance(member, property):
            rows.append((name, member, "property"))
        elif inspect.isfunction(member):
            rows.append((name, member, "method"))
    return rows


def render() -> str:
    lines = [
        "# rr_netconf_mgmt method catalog",
        "",
        "Generated by `scripts/gen_catalog.py` from the `rac_netconf_mgmt` submodule — do not edit by hand.",
        "The library is small: `NetconfDevice` owns the SSH/NETCONF session (ncclient) and",
        "`NetconfConfig` holds one configuration (XML + the YANG schemas needed to read it, via libyang).",
        "**[DESTRUCTIVE]** = writes to the device; needs explicit user confirmation.",
        "",
        "CLI: `netconf get|leaf|set|edit|state|rpc …` wrap these (see SKILL.md).",
        "",
    ]
    for cls in (NetconfDevice, NetconfConfig):
        lines += ["", f"## {cls.__name__}", "", " ".join((cls.__doc__ or "").split()), ""]
        for name, member, kind in members(cls):
            doc = member.fget.__doc__ if isinstance(member, property) else member.__doc__
            flag = " **[DESTRUCTIVE]**" if name in DESTRUCTIVE else ""
            tag = f" *({kind})*" if kind != "method" else ""
            lines.append(f"- `{name}{sig(member)}`{tag}{flag}  ")
            if first_line(doc):
                lines.append(f"  {first_line(doc)}")
    lines += ["", "## SchemaFetcherProtocol", "", " ".join((SchemaFetcherProtocol.__doc__ or "").split()), ""]
    for name, member, _ in members(SchemaFetcherProtocol):
        lines.append(f"- `{name}{sig(member)}`")
    lines += ["", "## Exceptions", ""]
    for name, obj in inspect.getmembers(exceptions, inspect.isclass):
        if issubclass(obj, Exception) and obj.__module__ == exceptions.__name__:
            base = obj.__bases__[0].__name__
            lines.append(f"- `{name}` (← {base})" + (f" — {first_line(obj.__doc__)}" if obj.__doc__ else ""))
    lines += [
        "",
        "## Constants",
        "",
        "- `DEFAULT_PORT = 830`, `DEFAULT_TIMEOUT = 30`, `DEFAULT_OPERATION = 'merge'`, `DEFAULT_DATASTORE = 'running'`",
        "- Namespaces: `urn:ietf:params:xml:ns:netconf:base:1.0`, `urn:ietf:params:xml:ns:yang:ietf-netconf-monitoring`",
        "",
    ]
    return "\n".join(lines) + "\n"


def main() -> None:
    text = render()
    if "--check" in sys.argv:
        if not OUT.is_file() or OUT.read_text() != text:
            sys.stderr.write(f"{OUT} is stale — run {Path(__file__).name}\n")
            sys.exit(1)
        print("methods.md is up to date")
        return
    OUT.write_text(text)
    print(f"wrote {OUT} ({text.count(chr(10))} lines)")


if __name__ == "__main__":
    main()
