#!/usr/bin/env python3
"""
Regenerate references/methods.md from the rr_ra2_mgmt sources (no network needed).

    python3 skills/api/scripts/gen_catalog.py            # rewrite references/methods.md
    python3 skills/api/scripts/gen_catalog.py --check    # exit 1 if the file is stale (CI / pre-commit)

The catalog is the offline map from "what I want to do" to "which Device/Helper method": one line
per method with its Python signature, the first docstring line and flags for public (no login) and
state-changing methods. Run it whenever the ra2_mgmt submodule is bumped.
"""

from __future__ import annotations

import importlib.machinery
import importlib.util
import inspect
import re
import sys
from pathlib import Path

SKILL_DIR = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(SKILL_DIR / "ra2_mgmt" / "src"))

_loader = importlib.machinery.SourceFileLoader("ra2cli", str(SKILL_DIR / "scripts" / "ra2"))
spec = importlib.util.spec_from_loader("ra2cli", _loader)
assert spec
ra2cli = importlib.util.module_from_spec(spec)
sys.modules["ra2cli"] = ra2cli  # dataclasses need the module registered before exec
_loader.exec_module(ra2cli)

from rr_ra2_mgmt.device import Device  # noqa: E402
from rr_ra2_mgmt.helper import Helper  # noqa: E402

OUT = SKILL_DIR / "references" / "methods.md"


def method_rows(cls: type, prefix: str) -> list[tuple[str, str, str, str, bool, bool]]:
    order = {n: i for i, n in enumerate(re.findall(r"^\s+def\s+([a-z][a-z0-9_]*)\s*\(", inspect.getsource(cls), re.M))}
    sections = ra2cli.sections_of(cls)
    rows = []
    for name, fn in sorted(ra2cli.public_methods(cls), key=lambda nf: order.get(nf[0], 10_000)):
        doc = fn.__doc__ or ""
        rows.append((
            sections.get(name, "Helper flows") if cls is Device else "Helper flows",
            prefix + name,
            ra2cli.signature_text(fn),
            ra2cli.first_line(doc),
            cls is Device and ra2cli.is_public(fn),
            ra2cli.is_destructive(name),
        ))
    return rows


def render() -> str:
    lines = [
        "# rr_ra2_mgmt method catalog",
        "",
        "Generated by `scripts/gen_catalog.py` from the `ra2_mgmt` submodule — do not edit by hand.",
        "Every `Device` method is a same-named RipEx2 RPC (`ra2 doc <name>` shows the API docs);",
        "it returns `Envelope[T]` with `.result`, `.warnings`, `.tstamp`. `helper.*` methods bundle",
        "multi-step flows (init+reconnect, start/poll/stop streams, condensed-data decoding).",
        "",
        "Flags: **[public]** works without credentials · **[DESTRUCTIVE]** changes device state,",
        "reboots it or destroys data — needs explicit user confirmation before you run it.",
        "",
        "CLI: `ra2 call <device-method> k=v…` · `ra2 helper <helper-method> k=v…` · `ra2 rpc <any-rpc> '{…}'`",
        "",
    ]
    section = None
    for sec, name, sig, summary, public, destructive in method_rows(Device, "") + method_rows(Helper, "helper."):
        if sec != section:
            section = sec
            lines += ["", f"## {sec}", ""]
        flags = (" **[public]**" if public else "") + (" **[DESTRUCTIVE]**" if destructive else "")
        lines.append(f"- `{name}{sig}`{flags}  ")
        if summary:
            lines.append(f"  {summary}")
    lines += [
        "",
        "## Documented RPCs not wrapped by the library",
        "",
        "Call these with `ra2 rpc <name> '{...}'` (params verbatim, raw envelope back):",
        "",
    ]
    for name in ra2cli.DOCS_ONLY_METHODS:
        flag = " **[DESTRUCTIVE]**" if ra2cli.is_destructive(name) else ""
        lines.append(f"- `{name}`{flag} — `ra2 doc {name} --full`")
    lines += [
        "",
        "## Session / lifecycle (not RPCs)",
        "",
        "- `Device(host, user='', password='', *, token='', timeout=30, retries=3, intermediate=None)`",
        "- `connect()` / `close()` / `reconnect()` — explicit session; `with Device(...) as d:` does the same.",
        "- Without `connect()` every call logs in and out on its own (per-call mode).",
        "",
    ]
    return "\n".join(lines) + "\n"


def main() -> None:
    text = render()
    if "--check" in sys.argv:
        if not OUT.is_file() or OUT.read_text() != text:
            sys.stderr.write(f"{OUT} is stale — run {Path(__file__).name}\n")
            sys.exit(1)
        print("methods.md is up to date")
        return
    OUT.write_text(text)
    print(f"wrote {OUT} ({text.count(chr(10))} lines)")


if __name__ == "__main__":
    main()
